### ISSUE TITLE
Personal Instance (Nextjs + Typescript) doesn't work 

### ISSUE THREAD

**Issue by mNutella** [serverless/cloud#180]
I created a new app based on your NextJS + Typescript template. I tried to use my **Personal Instance** to ensure it works and saw this [screenshot](https://user-images.githubusercontent.com/37267130/190878233-044231ba-0558-422d-bb55-07bf6e457371.png)

Personal Instance
https://outstanding-deploy-8uxua.cloud.serverless.com
Preview Instance
https://reliable-source-yhg33.cloud.serverless.com
Stage Instance
https://strong-source-2b7tm.cloud.serverless.com

**Comment by jeremydaly** [comment]
Hi @mNutella, this is how the system is intended to work. Your personal sandbox is optimized for fast syncing and backend deployments. The local developer server for Next.js gives you hot reloads and a much faster feedback loop for that framework. We proxy any backend service requests from your local machine (data, params, storage, etc.) that run in your SSR routes, as well as your /api requests, so you can develop locally. In order to run Next.js in the cloud, it requires a build step, which we automatically run when “sharing” to a preview instance or deploying to a stage.

From your project directory, run `cloud dev` and that will connect to your personal sandbox AND start your local Next.js server.

**Comment by mNutella** [comment]
Thank you @jeremydaly for the quick response - everything works fine!

I just was confused with the Personal Instance link and [documentation](https://www.serverless.com/cloud/docs/apps/apps-instances#developer-sandboxes-personal-instances) says that:
> Your developer sandbox gets its own public URL that you can use to test your application. 

If I understand correctly, the Personal Instance link is useless during local development in NextJS, right?

**Comment by jeremydaly** [comment]
Well, not useless. 😀

But yes, unless you have accompanying APIs that you're using outside your NextJS app, then you likely don’t need to access that url directly.
