### ISSUE TITLE
Clarity on developer instances

### ISSUE THREAD

**Issue by ac360** [serverless/cloud#3]
Please add clarity in the documentation whether a _Developer Instance_ is created for **every** _Service_, or does each developer have only one _Developer Instance_ which is replaced when they are working on multiple Services.

As a developer, I'm not as excited about having one Developer Instance that is overwritten when I work across multiple Services.  It adds a layer of complexity/worry that I will accidentally overwrite work-in-progress, in the case that I work on two Services simultaneously.  If Developer Instances are unique per Service, that would be ideal.

**Comment by jeremydaly** [comment]
Developer instances are unique **per service**, which will allow you to have your own sandboxed working copies that can communicate across services. I will update the documentation.

**Comment by dougmoscrop** [comment]
Are we still planning to have developer instances go away when you stop the session? I think so right? So the only way you have multiple developer instances is if you have multiple terminals going on?

**Comment by jeremydaly** [comment]
Probably not any time soon. Developers should be able to preserve their data across multiple sessions for now.

**Comment by ac360** [comment]
I personally wouldn't want Developer Instances to last only as long as the dev session.  

First, because it seems like this could go wrong and have bad consequences.  

Second, because I create test data 99% of the time while doing development and I don't want that to disappear and have to recreate it every time I sit down to to development work.

Third, because I will most likely share my Dev Instance URL.  I know there is a separate concept of Preview URLs, but tbh sharing a Dev Instance might be good enough 50% of the time for quick feedback.

Perhaps I'm missing something though.  What would be the benefit to the user of destroying their dev instance?

**Comment by jeremydaly** [comment]
We discussed this mostly in terms of reclaiming resources. We also floated the idea of using a local proxy (e.g. http://localhost:3000) to route to your developer instance as a way to better communicate the "local development" feel. This becomes slightly problematic if you're running multiple services at the same time, however. Different ports feels too easy.

Overall, we still want to draw a hard line between Developer Instances and Preview URLs, mostly for security purposes. We're still exploring ways to lock down these endpoints to keep your work protected from non-team members. For that reason, we're thinking that sharing your Developer Instance URL would be bad practice given how easy previews are.

And on the previews, the workflow needs to be part of the REPL implementation. I should be prompted when I type `cloud share` with an option to "update" recently shared previews.

**Comment by dougmoscrop** [comment]
I think there's a way to separate the concerns here.  I agree losing test data you just created is bad.  The idea would be your development instance might hibernate - we could back up your data, and whatnot. It's just, if your terminal isn't attached, the instance isn't on - things like schedule tasks don't need to fire, because it was just for you.  "If a developer instance is running in the cloud and there's nobody there to see it..."

Other people shouldn't have access to your development instance. It doesn't make sense to me to  be editing things live and having someone else interacting with it - that's why you can share a snapshot of your instance via `share` -- it's to freeze it in time for someone to look at, and if they find a bug and you fix it, that's why you can easily, instantly, copy your code to that shared instance again.

**Comment by dougmoscrop** [comment]
I want `cloud start` to feel synonymous with `npm start` - it's local but it's not, we're blurring the lines.   Basically, developer instances _aren't_ instances per se, they're just backed by ephemeral instances to give you access to the real cloud services you want to develop against -- they shouldn't show up in any lists, or be visible anywhere but your IDE/terminal. If you want other people to interact with it, `share` it with them.  Let's iron out the details of what makes that experience great - such as, for example, streaming your changes to data to your local machine (like a continuous export) so that the next time you run `cloud start` you pick up **right** where you left off.  Does that make any sense?

**Comment by ac360** [comment]
Hmm, I can't yet see the value to the user in these concepts.

I'm a fan of the dev-in-the-cloud experience (if it has the speed of local) for the sole reason my dev environment would match my app's production environment identically, avoiding all surprises when promoting to production.  But once we start distorting that dev experience to auto-delete apps/data, shut off background tasks, add new permissions concepts, etc., it feels like we're back at square one.  Let my dev instance live in peace! ;)

**Comment by jeremydaly** [comment]
The parity of instances is definitely non-negotiable 😉.

The other bits are just finding the right workflow and ensuring optimal development paths. Enabling "development environment clean up" isn't a new concept (e.g. local dev becomes unavailable once you stop your local emulator and PR and feature branches get automatically deleted when merged). Some of these existing workflows can be challenged, and some of them have become best practices for good reason.

Ultimately, this should all be transparent to the user. But certain things, like limited access to your own private dev instance, will ensure that users aren't sharing a URL to an app that will change every time a user saves their work, or that "preview URLs" don't become a substitute (or a permissions workaround) for permanent stages by expiring them after a time (or perhaps even limiting access). As long as none of these things affect the parity of the execution environments, then they're all worth exploring. I don't think that puts us back to square one, I think it gives us an opportunity to reduce developer friction and give teams more freedom (and confidence) by ensuring the security of WIP applications.
